/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tastefuljava.simili.ui;

import org.tastefuljava.simili.model.Patch;
import org.tastefuljava.simili.model.Schema;

/**
 *
 * @author maurice
 */
public class SchemaEditorFrame extends javax.swing.JFrame {

    /**
     * Creates new form SchemaEditorFrame
     */
    public SchemaEditorFrame() {
        initComponents();
        Schema schema = new Schema();
        Patch patch = new Patch();
        patch.setTitle("Sample Patch");
        patch.setPosition(20, 20);
        patch.newInput("input 1");
        patch.newInput("input 2");
        patch.newOutput("output 1");
        patch.newOutput("output 2");
        patch.newOutput("output 3");
        schema.addPatch(patch);
        schemaView.setSchema(schema);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schemaView = new org.tastefuljava.simili.ui.SchemaView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(schemaView);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.tastefuljava.simili.ui.SchemaView schemaView;
    // End of variables declaration//GEN-END:variables
}
